mysite/home/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.home, name='homepage'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^(?P<username_id>[0-9]+)/$', views.profile, name='profile'),

    url(r'^login/$', auth_views.login, name='login'),

    url(r'^logout/$', auth_views.logout, name='logout'),

    url(r'^admin/$', admin.site.urls),

    # add an item
    url(r'^item/add/$', views.ItemCreate.as_view(success_url="/home/"), name='item-add'),

    # update an item
    url(r'item/(?P<pk>[0-9]+)/$', views.ItemUpdate.as_view(), name='item-update'),

    # url(r'^(?P<username_id>[0-9]+)/$', views.ItemCreate.as_view(), name='item-add'),

    # delete an item
    # url(r'item/(?P<pk>[0-9]+)/delete/$', views.ItemDelete.as_view(), name='item-delete'),

]

# urlpatterns = [
#     url(r'^$', views.HomeView.as_view(), name='home'),
#
#     url(r'^(?P<pk>[0-9]+)/$', views.ProfileView.as_view(), name='profile'),
#
#     # url(r'^home/add/$', views.ProfileView.as_view(), name='item-add'),
# ]







mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/home/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone


class User(models.Model):
    username = models.CharField(max_length=21)
    password = models.CharField(max_length=26)
    name = models.CharField(max_length=100)
    degree = models.CharField(max_length=100, blank=True, help_text='Leave blank if personnel/faculty')
    office = models.CharField(max_length=100, blank=True, help_text='Leave blank if student')

    def get_absolute_url(self):
        return reverse('home:homepage', kwargs={'pk': self.pk})

    def __str__(self):
        return self.username

item_Type = (
    ('Academic Use', 'Academic Use'),
    ('Office Use', 'Office Use'),
)


class Item(models.Model):
    userName = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(primary_key=True, max_length=300)
    photo = models.FileField()
    quantity = models.PositiveIntegerField(default=1)
    condition = models.CharField(max_length=200)
    itemType = models.CharField(max_length=100, choices=item_Type, default='Academic Use')
    courseName = models.CharField(max_length=100, blank=True, help_text='Leave blank if Office Use')
    pub_date = models.DateTimeField('date published')

    # def choice(self):
    #     if self.

    def get_absolute_url(self):
        return reverse('home:homepage', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Tags(models.Model):
    name = models.ForeignKey(Item, on_delete=models.CASCADE)
    tag = models.CharField(max_length=100)
    
    def __str__(self):
        return self.tag

mysite/home/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'name', 'degree', 'office']

mysite/home/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.shortcuts import render, get_object_or_404
from .models import User, Item, Tags
from .forms import UserForm


def home(request):
    latest_item_list = Item.objects.order_by('-pub_date')
    latest_tag_list = Tags.objects.all()
    context = {'latest_item_list': latest_item_list,
               'latest_tag_list': latest_tag_list,
               }
    return render(request, 'home/home.html', context)


def profile(request, username_id):
    user = get_object_or_404(User, pk=username_id)
    latest_item_list = Item.objects.order_by('-pub_date')
    latest_tag_list = Tags.objects.all()
    context = {'user': user,
               'latest_item_list': latest_item_list,
               'latest_tag_list': latest_tag_list,
               }
    return render(request, 'home/profile.html', context)


class ItemCreate(CreateView):
    model = Item
    fields = ['userName', 'name', 'photo', 'quantity', 'condition', 'itemType', 'courseName', 'pub_date']

# def ItemCreate(ModelForm):
#
#     class Meta:
#         model = Item


class ItemUpdate(UpdateView):
    model = Item
    fields = ['userName', 'name', 'photo', 'quantity', 'condition', 'itemType', 'courseName', 'pub_date']


class ItemDelete(DeleteView):
    model = Item
    success_url = reverse_lazy('home:homepage')


class UserFormView(View):
    form_class = UserForm
    template_name = 'home/registration_form.html'

    # display a blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def get(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # clean (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User objects if correct credentials
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    success_url = reverse_lazy('home:homepage')
                    # return redirect('home:homepage')

        return render(request, self.template_name, {'form': form})



mysite/home/templates/home/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}New Beginnings Marketplace{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css'%}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:homepage' %}">New Beginnings Marketplace</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'home:homepage' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'home:item-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Post an Item
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'home:register' %}">
                        <span class="glyphicon glyphicon-registration-mark" aria-hidden="true"></span>&nbsp; Register
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

mysite/home/templates/home/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

mysite/home/templates/home/home.html
{% extends 'home/base_template.html' %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:homepage' %}">New Beginnings Marketplace</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'home:homepage' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Post an Item
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'home:register' %}">
                        <span class="glyphicon glyphicon-registration-mark" aria-hidden="true"></span>&nbsp; Register
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

{% block body %}

<body class="body" style="background-color:#f6f6f6">

    <br/>
    <br/>

<div class="container">

{#    {% if all_items %}#}
{#        {% for item in all_items %}#}
    {% if latest_item_list %}
        {% for item in latest_item_list %}
          <div class="col-md-2">
                <div class="thumbnail">
                    <img src="{{ item.photo.url }}" class="img-thumbnail" />
                     <div class="caption">

                        <h3>{{ item.name }}</h3><h6><a href="{% url 'home:profile' item.userName.id %}">{{ item.userName }}</a></h6>

                        <p>{{ item.condition }}<br/><b>Type: {{ item.itemType }}</b></p>

                         <h6>
                             {% for tags in latest_tag_list %}
                                  {% if tags.itemName.id == item.id %}
                                        #{{ tags.tag }}&nbsp;
                                  {% endif %}
                             {% endfor %}
                         </h6>

{#                         <form action="{% url 'home:item-delete' item.name.id %}" method="post" style="display: inline;">#}
{#                                {% csrf_token %}#}
{#                                <input type="hidden" name="item_name_id" value="{{ item.name.id }}"/>#}
{#                                <button type="submit" class="btn btn-default btn-sm">#}
{#                                    <span class="glyphicon glyphicon-trash"></span>#}
{#                                </button>#}
{#                         </form>#}

                     </div>
                 </div>
          </div>
        {% endfor %}

    {% else %}
        <p>No item available</p>

    {% endif %}

</div>

    <center>
        <button type="load" class="btn btn-inverse">Load More</button>
    </center>

</body>

{% endblock %}


mysite/home/templates/home/item_form.html
{%  extends 'home/base_template.html' %}
{% block title %}Add a New Item{% endblock %}
{% block item_active %}active{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'home/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
             </div>
        </div>
    </div>

{% endblock %}

mysite/home/templates/home/login.html
{%  extends 'home/base_template.html' %}
{% block title %}Login{% endblock %}

{% block content %}
   <h2 href="{% url 'home:login' %}">Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

mysite/home/templates/home/profile.html
{% extends 'home/base_template.html' %}
{% block title %}User Profile{% endblock %}

<html>

	<title>User Profile</title>

{% block body %}
    <div class="page-header">
        <center><h1>{{ user.name }}</h1></center>
    </div>

    <br/><br/>
    <center>
    <ul class="list-group">
        <li class="list-group-item"><b>Username:</b> {{ user.username }}</li>
        <li class="list-group-item"><b>Degree:</b> {{ user.degree }}</li>
        <li class="list-group-item"><b> Office:</b> {{ user.office }}</li>
    </ul>
    </center>

    <div class="container">
        {% for item in latest_item_list %}
            {% if item.userName.id == user.id %}
                <div class="col-md-2">
                  <div class="thumbnail">
                    <a href="#"><img src="{{ item.photo.url }}" class="img-thumbnail" /></a>
                    <div class="caption">
                    <h3>{{ item.name }} ({{ item.quantity }})</h3>
                      <h6><a href="/home/{{ item.userName.id }}/">{{ item.userName }}</a></h6>
                    <p>{{ item.condition }}<br/>
                        <b>Type: {{ item.itemType }}</b>
                        <br/>
                        <b>{{ item.courseName }}</b></p>

                      <h6>
                      {% for tags in latest_tag_list %}
                          {% if tags.itemName.id == item.id %}
                            #{{ tags.tag }}&nbsp;
                          {% endif %}
                      {% endfor %}
                      </h6>

                    </div>
                  </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

mysite/home/templates/home/registration_form.html
{%  extends 'home/base_template.html' %}
{% block title %}Register{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'home/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Sign-Up</button>
                            </div>
                        </div>
                    </form>
                </div>
             </div>
        </div>
    </div>

{% endblock %}